package com.bss.sample.app.bbdd.jpa;
// Generated 17-feb-2017 15:47:50 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userprofile generated by hbm2java
 */
@Entity
@Table( name = "userprofile", catalog = "conmigodb" )
public class Userprofile implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String userId;
	private String email;
	private String firstName;
	private String lastName;
	private String name;
	private String username;

	public Userprofile() {
	}

	public Userprofile( final String userId ) {
		this.userId = userId;
	}

	public Userprofile( final String userId, final String email, final String firstName, final String lastName, final String name, final String username ) {
		this.userId = userId;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.name = name;
		this.username = username;
	}

	@Id

	@Column( name = "userId", unique = true, nullable = false )
	public String getUserId() {
		return userId;
	}

	public void setUserId( final String userId ) {
		this.userId = userId;
	}

	@Column( name = "email" )
	public String getEmail() {
		return email;
	}

	public void setEmail( final String email ) {
		this.email = email;
	}

	@Column( name = "firstName" )
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName( final String firstName ) {
		this.firstName = firstName;
	}

	@Column( name = "lastName" )
	public String getLastName() {
		return lastName;
	}

	public void setLastName( final String lastName ) {
		this.lastName = lastName;
	}

	@Column( name = "name" )
	public String getName() {
		return name;
	}

	public void setName( final String name ) {
		this.name = name;
	}

	@Column( name = "username" )
	public String getUsername() {
		return username;
	}

	public void setUsername( final String username ) {
		this.username = username;
	}

}
